name: spot
description: Find local video posts
version: 1.4.2+64
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  camera: ^0.11.3
  flutter_bloc: ^9.1.1
  google_maps_flutter: ^2.10.0
  video_player: ^2.0.2
  flutter_ffmpeg: ^0.4.2
  path_provider: ^2.0.1
  geolocator: ^14.0.2
  flutter_feather_icons: ^2.0.0+1
  flutter_secure_storage: ^10.0.0
  image_picker: ^1.2.1
  flutter_cache_manager: ^3.0.1
  flutter_markdown: ^0.7.7+1
  rxdart: ^0.28.0
  geocoding: ^4.0.0
  share: ^2.0.1
  firebase_core: ^4.4.0
  firebase_analytics: ^12.1.1
  flutter_video_info: ^1.2.0
  shared_preferences: ^2.0.6
  google_maps_cluster_manager_2: ^3.2.0
  firebase_auth: ^6.1.4
  cloud_firestore: ^6.1.2
  firebase_storage: ^13.0.6
  cloud_functions: ^6.0.6
  geoflutterfire_plus: ^0.0.34

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^10.0.0
  mocktail: ^1.0.4
  very_good_analysis: ^10.1.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7

flutter:
  assets:
    - assets/images/
    - assets/md/
  uses-material-design: true
  generate: true

flutter_icons:
  android: true
  ios: true
  image_path: 'assets/launcher/icon.png'
  adaptive_icon_foreground: 'assets/launcher/foreground.png'
  adaptive_icon_background: 'assets/launcher/background.png'
